dist: trusty
sudo: required
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

addons:
  apt:
    packages:
    - samba
    - smbclient
    - libsmbclient-dev
    - libsmbclient

env:
  global:
    - CURRENT_DIR=`pwd`
  matrix:
    - BACKEND=smbclient
    - BACKEND=libsmbclient

before_install:
  - pass=$(perl -e 'print crypt("test", "password")')
  - sudo useradd -m -p $pass test
  - if [ "$BACKEND" == 'libsmbclient' ]; then ./install_libsmbclient.sh; fi
  - cd $CURRENT_DIR
  - chmod go+w $HOME
  - printf "%s\n%s\n" test test|sudo smbpasswd -a -s test
  - sudo mkdir /home/test/test
  - sudo chown test /home/test/test
  - |
    echo "[test]
    comment = test
    path = /home/test
    guest ok = yes
    writeable = yes
    map archive = yes
    map system = yes
    map hidden = yes
    create mask = 0777
    inherit permissions = yes" | sudo tee -a /etc/samba/smb.conf
  - sudo service smbd restart
  - testparm -s

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - cd tests
  - phpunit --coverage-clover ../build/logs/clover.xml --configuration phpunit.xml

after_script:
 - cd $CURRENT_DIR
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
