dist: bionic
sudo: required
language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

addons:
  apt:
    packages:
    - samba
    - smbclient
    - libsmbclient-dev
    - libsmbclient

env:
  global:
    - CURRENT_DIR=`pwd`
  matrix:
    - BACKEND=smbclient
    - BACKEND=libsmbclient

before_install:
  - pass=$(perl -e 'print crypt("test", "test")')
  - sudo useradd -m -p $pass test
  - if [ "$BACKEND" == 'libsmbclient' ]; then ./install_libsmbclient.sh; fi
  - cd $CURRENT_DIR
  - chmod go+w $HOME
  - printf "%s\n%s\n" test test|sudo smbpasswd -a -s test
  - sudo mkdir /home/test/test
  - sudo chown test /home/test/test
  - |
    echo "[test]
    comment = test
    path = /home/test
    guest ok = yes
    writeable = yes
    map archive = yes
    map system = yes
    map hidden = yes
    create mask = 0777
    inherit permissions = yes" | sudo tee -a /etc/samba/smb.conf
  - sudo service smbd restart
  - testparm -s

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml -c tests/phpunit.xml
  - vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --diff --diff-format udiff

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover clover.xml
